site_name: todo
theme: material

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - About: about.md
  - Tutorials: tutorials.md
  - How-To guides: how-to-guides.md
  - reference.md
  - explanation.md
