# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
    paths: ["todo-go/**"]
  pull_request:
    branches: ["main"]
    paths: ["todo-go/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "1.25"

      - name: Build
        run: cd todo-go && go build -v ./...

      - name: Test
        run: cd todo-go && go test -v ./...
