name: Python Tests

on:
    push:
        branches:
            - main
        paths:
            - todo-python/**
    pull_request:
        paths:
            - todo-python/**

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version:
                    - "3.12"
        defaults:
            run:
                working-directory: ./todo-python

        steps:
            - name: Checkout source
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            - name: Cache tox
              uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
              with:
                  path: .tox
                  key: tox-${{hashFiles('pyproject.toml') }}

            - name: Set up python
              uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: pip
                  cache-dependency-path: pyproject.toml

            - name: Install dependencies
              run: python -m pip install tox tox-gh-actions

            - name: Test with tox
              run: tox

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: milanmlft/todo
