name: Python Linting

on:
    push:
        branches:
            - main
        paths:
            - todo-python/**
    pull_request:
        paths:
            - todo-python/**
            
jobs:
    linting:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./todo-python
        steps:
            - name: Checkout source
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            - name: Cache pre-commit
              uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4
              with:
                  path: ~/.cache/pre-commit
                  key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

            - name: Set up python
              uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
              with:
                  python-version: "3.x"
                  cache: pip
                  cache-dependency-path: pyproject.toml

            - name: Install dependencies
              run: python -m pip install pre-commit

            - name: Run pre-commit
              run: pre-commit run --all-files --color always --verbose
